/**
 * Builds apps/legacy-registry/preview/ from client/.
 *
 * The preview exists for one reason: the sandboxed iframe used for shareable
 * preview links has no IndexedDB, so the real offline queue cannot run there. A
 * hand-maintained copy of the client drifts out of date the moment anyone edits
 * the real one — which had already happened — so the preview is generated
 * instead, and the only difference from the real app is the one file that has
 * to differ.
 *
 * Run: node apps/legacy-registry/scripts/build-preview.mjs
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const CLIENT = join(here, "..", "client");
const PREVIEW = join(here, "..", "preview");

/**
 * The real offline queue is replaced by the stub that reports it cannot hold
 * anything back. The stub is kept in client/ next to the real one so the two
 * stay visible side by side and neither can be edited in ignorance of the other.
 */
const SWAP = { "offline-queue.js": "offline-queue-unavailable.js" };

/** Never shipped to the preview: the source of the swap, and the service worker. */
const SKIP = new Set([
  "offline-queue-unavailable.js",
  // The service worker caches the app for genuine offline use on a real device.
  // In the preview it would serve stale files after a redeploy and confuse
  // testing, and offline use is exactly what the preview cannot demonstrate.
  "sw.js",
]);

rmSync(PREVIEW, { recursive: true, force: true });
mkdirSync(PREVIEW, { recursive: true });

let copied = 0;
let swapped = 0;

for (const name of readdirSync(CLIENT)) {
  if (SKIP.has(name)) continue;
  if (!statSync(join(CLIENT, name)).isFile()) continue;

  const source = SWAP[name] ?? name;
  if (SWAP[name]) {
    writeFileSync(join(PREVIEW, name), readFileSync(join(CLIENT, source)));
    swapped += 1;
  } else {
    copyFileSync(join(CLIENT, name), join(PREVIEW, name));
    copied += 1;
  }
}

/*
 * The service worker was skipped, so the registration call has to go too, or
 * every preview load fails to fetch it and logs an error the tester will
 * reasonably mistake for a real fault.
 */
const indexPath = join(PREVIEW, "index.html");
let html = readFileSync(indexPath, "utf8");
const before = html;
html = html.replace(
  /navigator\.serviceWorker\.register\([^)]*\)[^;]*;/g,
  "/* service worker omitted from the preview build */;",
);
if (html !== before) writeFileSync(indexPath, html);

writeFileSync(
  join(PREVIEW, "PREVIEW-ONLY.txt"),
  [
    "Generated by scripts/build-preview.mjs — do not edit by hand.",
    "",
    "This is apps/legacy-registry/client with two changes, both forced by the",
    "sandboxed preview iframe:",
    "",
    "  offline-queue.js  replaced by the stub that reports storage unavailable,",
    "                    because the iframe has no IndexedDB",
    "  sw.js             omitted, along with its registration call",
    "",
    "Everything else is byte-for-byte the real app. Offline capture works on a",
    "real device and cannot be demonstrated here.",
    "",
    `Built ${new Date().toISOString()}`,
    "",
  ].join("\n"),
);

console.log(
  `preview built: ${copied} files copied, ${swapped} swapped, ${SKIP.size} skipped` +
    (html !== before ? ", service-worker registration removed" : ""),
);
